from datetime import datetime
from pprint import pprint
import functools
from uuid import uuid4
import json
from app import db
from app.dbase.models import DBOrder


class BaseMessage():

	_integerAttributes = ('price', 'volume')
	_settable_message_attributes = ('owner', 'received')
	_autogenerated_attributes = ('created_at', 'uuid')

	def __init__(self, subclass_attributes, **kwargs):
		self.created_at = datetime.utcnow()
		self.uuid = uuid4()
		self._all_settable_attributes = tuple(list(self._settable_message_attributes) + list(subclass_attributes))
		self._all_attributes = tuple(list(self._all_settable_attributes) + list(self._autogenerated_attributes))
		
		self._set_received_attributes(**kwargs)	
		self._init_integer_fields()
		

	def get_attributes(self):
		return dict(map(lambda attr: (attr, getattr(self, attr)), self._all_attributes))

	def __repr__(self):
		return str(self.get_attributes())
	
	def _init_integer_fields(self):
		for attr in self._integerAttributes: setattr(self, attr, int(getattr(self, attr)))

	def _set_received_attributes(self, **kwargs):
		self.__dict__.update(dict(map(lambda key: (key, kwargs.get(key, None)), self._all_settable_attributes)))

	
	
	def get_json(self):
		data = self.get_attributes()
		data['received'] = data['received'].strftime('%Y-%m-%d-%H:%M')
		return json.dumps(data)


class Transaction(BaseMessage):

	# _allowed_transaction_attributes = ['buyer', 'seller', 'sell_order', 'buy_order', 'price', 'volume']
	def __init__(self, buy_order, sell_order):
		assert isinstance(order1, Order) and isinstance(order2, Order), 'Transaction is initilaized by passing two order objects'
		BaseMessage.__init__(self, *self._allowed_transaction_attributes, **kwargs)
		




@functools.total_ordering
class Order(BaseMessage):

	BUY = 'buy'
	SELL = 'sell'
	LIMIT = 'limit'
	MARKET = 'market'
	_settable_order_attributes = ('price', 'volume', 'order_type', 'side')

	def __init__(self, **kwargs):
		BaseMessage.__init__(self, self._settable_order_attributes, **kwargs)
		# db.session.add(DBOrder(**self.get_attributes()))
		# db.session.commit()
	
	def breed(self, child_volume):
		child = Order(**self.get_attributes())
		# map(lambda attr: setattr(child, attr, getattr(self, attr)), self._allowedAttributes)
		child.volume = child_volume
		return child

	def is_sell(self):
		if self.side == self.SELL: return True
		else: return False

	def is_buy(self):
		if self.side == self.BUY: return True
		else: return False

	def is_limit(self):
		if self.order_type == self.LIMIT: return True
		else: return False

	def is_market(self):
		if self.order_type == self.MARKET: return True
		else: return False 

	def is_cheaper(self, other_order):
		if self.price < other_order.price: return True

	def get_details(self):
		return '%s order for %s shares at price %s'%(self.side, self.volume, self.price)

	def __eq__(self, other_order):
		return isinstance(self, other_order.__class__) and self.price == other_order.price

	def __gt__(self, other_order):
		return self.price > other_order.price

	